### ISSUE TITLE
Does this API still work?

### ISSUE THREAD

**Issue by technobly** [gabrielecirulli/cleverbot-api#3]
I tried running this on https://c9.io as a ruby gem and also as a rails app.  Both didn't seem to connect to the cleverbot server.

I could give you access to my workspace on Cloud9 if you would like to take a look.  Just give me your email address.  Otherwise, if you have a preferred method for running this please share.

Thanks!

**Comment by technobly** [comment]
Here's what it looks like:
http://i.imgur.com/ZBzdHek.png

**Comment by gabrielecirulli** [comment]
Thanks for the heads up. I'll have a look.

**Comment by gabrielecirulli** [comment]
It looks like they changed the address for their endpoint. It should be working fine now. If you still get an error, make sure you're not using Ruby 2.0 because I noticed there might still be some issues with that version (I get this with `ruby 2.0.0p0 (2013-02-24 revision 39474)`).

**Comment by gabrielecirulli** [comment]
I've pushed a new version of the gem with the fix.

**Comment by technobly** [comment]
Thank you so much!  It's working :) I'm going to be implementing this on a Node.js application, so wish me luck! 

LMAO
http://i.imgur.com/44gQ4xk.png

and more:
http://i.imgur.com/ToP1AgS.png

**Comment by technobly** [comment]
@gabrielecirulli could you point me in the right direction with the URL formatting?  Once I get that I'll be able to use HTTP.GET fairly easily via Node.js

This seems to do something:
http://www.cleverbot.com/webservicemin/start="y"&icognoid="wsf"&fno="0"&sub="Say"&islearning="1"&cleanslate="false"

But this not so much:
http://www.cleverbot.com/webservicemin?start=y&icognoid=wsf&fno=0&sub=Say&islearning=1&cleanslate=false

**Comment by gabrielecirulli** [comment]
You have to perform the requests as POST, not GET. Send the query string, url-encoded, in the request body (instead of as part of the URL). You also don't need quotes around the values, so you might want to strip those.  You'll also have to include the "stimulus" parameter which represents your input to CleverBot (it can be left empty) and "icognocheck", which is a string used by the system to check the validity of your request. To build the icognocheck string you need to take your current query string (in the `key1=value1&key2=value2` format) and calculate the MD5 hash of the 20 characters after the 9th (in Javascript you could use `queryString.substr(9, 20)` to get said characters). After you have the icognocheck, you just append that to the query string as well and send the entire thing. You should get a valid response containing many fields separated by "\r". If you split the string using "\r" you can then extract each field. You will have to memorise them in your query string for your subsequent requests (like I've done at https://github.com/gabrielecirulli/cleverbot-api/blob/master/lib/cleverbot-api.rb#L47). The ttsText field of the response is cleverbot's response to your input. 

Hope this helps.

**Comment by technobly** [comment]
That helps a ton, thanks!  I'll let you know if I get it working.

**Comment by technobly** [comment]
Got it working and holding separate conversations with multiple people at once :)  Thanks for your help!

BTW even though I added the MD5 Hash, I noticed that it's always the same value as long as your query string from character 9-28 stays the same (which is pretty easy to control).  I'm still just doing the MD5 Hash anyway to be technically correct, or in case it changes and I need it.

**Comment by gabrielecirulli** [comment]
Yeah, that's true. If you decide to put your library on Github I can add a link to it in this repo's readme, since a Javascript implementation is still missing.

**Comment by technobly** [comment]
@gabrielecirulli here's my NodeJS version for Turntable.fm bots :)
https://github.com/DubbyTT/Clever

Not exactly just the API, but the core of it is there and pretty easy to modify for anything.
