### ISSUE TITLE
I'm getting a "403 Forbidden" message

### ISSUE THREAD

**Issue by technobly** [gabrielecirulli/cleverbot-api#4]
It's been working great but now I'm getting a "403 Forbidden" message when I look at the response from the HTTP POST... any idea what's going on?

Seems like a lot of changes on their website... I have no idea looking at their source code what has changed though.  Maybe you are more familiar with it? :)

**Comment by gabrielecirulli** [comment]
Sorry for the late response. Is this your custom API or the code from this repository? I currently can't have a thorough look at it, but these issues are caused by CleverBot changing their interface slightly over time (probably to make APIs stop working). If that's the case, you might have luck by analyzing the operations and requests the JavaScript code loaded on the homepage of CleverBot does when you send a message. Maybe they just changed the URL to query, who knows.

**Comment by technobly** [comment]
It just started working again all by itself! I had added try/catch code to to response to keep it from crashing. Ill try to release my JavaScript wrapper for nodejs sometime soon.

**Comment by technobly** [comment]
Their API must have just been down for a bit.

**Comment by jimgao1** [comment]
Is it possible that I have been banned by sending lots of requests?
